"""IDaaS adapter domain constants."""

from cloud_idaas.adapter.aws.domain.constants import (
    AWS_ACCESS_KEY_ID,
    AWS_EXPIRATION,
    AWS_SECRET_ACCESS_KEY,
    AWS_SESSION_TOKEN,
    AWS_STS_TOKEN,
    CLOUD_ACCOUNT_ROLE_ACCESS_CREDENTIAL,
    CLOUD_ACCOUNT_ROLE_EXTERNAL_ID,
    OBTAIN_ACCESS_CREDENTIAL_PATH,
)

__all__ = [
    "AWS_STS_TOKEN",
    "CLOUD_ACCOUNT_ROLE_ACCESS_CREDENTIAL",
    "CLOUD_ACCOUNT_ROLE_EXTERNAL_ID",
    "OBTAIN_ACCESS_CREDENTIAL_PATH",
    "AWS_ACCESS_KEY_ID",
    "AWS_EXPIRATION",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_SESSION_TOKEN",
]
